# Config file will contain all the code that is used for generating logs
# Variables and parameters will be changed here to affect generator.ps1

# -----------------------------
# Services and Event Definitions
# -----------------------------
## HASHTABLE ##
$Services = @{
    "system" = @{
        "events" = @("startup","shutdown","update","error")
        "errorRate" = 0.05   # 5% of events are errors
    }
    "access" = @{
        "events" = @("login","logout","invalidPassword","invalidUsername","passwordChange")
        "errorRate" = 0.1    # 10% of events are errors
    }
    "app" = @{
        "events" = @("start","stop","exception","crash","restart")
        "errorRate" = 0.08   # 8% of events are errors
    }
}
#EXAMPLE USAGE#
<#
$Services["access"]["events"]
Output: login logout invalidPassword invalidUsername passwordChange
$Services["app"]["errorRate"]
Output: 0.08
#>
#----------#  Paths #----------#
$LogPath = "$PSScriptRoot/data/logs/"          # Where generated logs are stored
$AnalysisPath = "$PSScriptRoot/data/analysis/" # Where analysis reports go


#----------# Generator Defaults #----------#
$DefaultBatchSize = 1000     # Number of events for batch mode
$DefaultEventsPerSecond = 5              # Events per second for streaming mode
$DefaultDuration = 120       # Duration in seconds for streaming mode
$EnableBadActorDefault = $false  # Whether bad actor events are generated by default

#----------# Analyzer Thresholds #----------#
$ErrorThresholdPerMinute = 10       # Number of errors per minute to trigger alert
$FailedLoginThreshold = 3           # Number of failed logins per user to trigger alert
$AnomalyCheckInterval = 60          # Interval in seconds to check for anomalies in streaming

#----------# Other Settings #----------#
$AllowedLogTypes = @("system","access","app")  # Default log types generator/analyzer will use

# You can add more settings here as the project grows:
# - Dashboard refresh rates
# - Alert email settings
# - Log rotation limits
# - Output formats (JSON, CSV, text)
# - Anything else that is needed that we would want to change for both analyzer and generator at the same time
